# Generated by Django 6.0.7 on 2026-08-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_download_logs', to='analytics.visitor')),
            ],
            options={
                'verbose_name': 'Resume Download',
                'verbose_name_plural': 'Resume Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
